### ISSUE TITLE
Instabilité de l'application : problème de chargement des versions d'un article

### ISSUE THREAD

**Issue by antoinentl** [EcrituresNumeriques/stylo#389]
Depuis hier suite aux tests du déploiement du temps réel #380, et malgré les correctifs appliqués #386, il y a une instabilité dans l'application.

Bug constaté par @Mmellet avec vidéo ci-dessous. Parfois cliquer sur une version ancienne de l'article m'amène à un mode read-only, parce qu'il fait changer de compte : exemple, je suis sur un article du compte **A**, je consulte une version que je viens de sauvergarder, Stylo charge/load pendant un long moment puis m'affiche la version en read only en m'indiquant que **A** est connecté. Si je regarde ma barre d'utilisateur, il m'a rétrogradé dans le compte **B**. Ce qui est un problème parce que justement l'article en question n'est accessible en édition juste à partir du compte **A**. le compte **B** ne devrait pas y avoir accès en édition. Cet article n'a pas été partagé avec le compte **B**.

https://user-images.githubusercontent.com/6869488/119152408-47200c80-ba1e-11eb-8cfd-337f0da7c6f0.mp4

Est-ce un problème de cache ? Ce problème nous empêche de travailler pour l'instant.

**Comment by ggrossetie** [comment]
Il y a 3 problèmes distincts : 

#### Stylo n'arrive pas à charger le contenu d'une version

Quand on clique sur une version, Stylo n'arrive pas à charger le contenu.
Dans la console on peut voir l'erreur : 

```
Uncaught (in promise) TypeError: Cannot read property 'md' of undefined
```

Cela correspond à cette ligne: 

https://github.com/EcrituresNumeriques/stylo/blob/7464747fbea2d7e9c83bb3b86aa45c95f3c95567/front/gatsby/src/components/Write/Write.jsx#L208

#### Le message "read-only" est perturbant

Quand on clique sur une version, on passe en mode "read-only" qui affiche le message générique : "This article is in read-only mode because a user is currently editing it." alors que dans ce cas on est simplement en lecture seule car on est plus en édition (on consulte l'historique).

#### Quand on clique sur "Back to edit mode" on obtient une erreur

Quand on clique sur "Back to edit mode" on obtient une erreur : "Error Article not found."
Dans la console on peut voir :

```
Version id 0123456789ab does not exist".
```

La version "0123456789ab" correspond à la valeur par défaut, cela veut dire qu'on récupère mal l'identifiant de la version "en cours".

Je vais isoler les changements de la version 1.3.1 dans une branche et revert la branche principale sur la version 1.2.1 afin de redéployer cette version en production.

**Comment by ggrossetie** [comment]
Revert en production et corrigé dans https://github.com/EcrituresNumeriques/stylo/commit/061bab376ed7ab6347d75f6c3268d5a151df647f
