### ISSUE TITLE
Mise à jour des présentations autour de Stylo

### ISSUE THREAD

**Issue by DMathelier** [EcrituresNumeriques/stylo#430]
Mise à jour de la page Ressources de la documentation de Stylo : nouvelles présentations à ajouter et liens morts à corriger

**Comment by thom4parisot** [comment]
@Mogztter a partagé cette bio avec @antoinentl :

> Guillaume is an enthusiastic software developer with over a decade of experience in the field with a strong Java background. He is curious about and loves to learn new languages, tools, and techniques.
In recent years, he has worked on a wide range of projects using a variety of programming languages: Java, Scala, Kotlin, JavaScript, Ruby, Go, Python. 
Guillaume contributes to many open-source projects and has been an active member of the Asciidoctor community since 2013.

Et voici la mienne : 

<pre><code>
I design and develop open source digital services with a user-centric approach, in multidisciplinary teams.
I focus my efforts on environmental projects, knowledge sharing and independant community spaces.
I authored the book "Node.js, learning by doing" [^1].

On my spare time, I bake sourdough bread for friends and family, hike and camp in the surroundings.

I used to [work at BBC R&D](https://www.bbc.co.uk/rd/people/thomas-parisot) in London,
and I have been involved in the [Sud Web conference](https://sudweb.fr).

- **Main website**: https://oncletom.io
- **Professional website**: https://détour.studio

[^1]: Parisot, T. (2018). _Node.js : bonnes pratiques pour la programmation Javascript applicative et modulaire_. Paris, France: Eyrolles.
</pre></code>

**Comment by antoinentl** [comment]
@oncletom Pour info ce ticket ne concernait pas les bios mais elles me seront utiles :+1:
